language: java

jdk:
  - openjdk8
  - openjdk11
  - openjdk17

deploy:
  - provider: releases
    token: "$GITHUB_API_KEY"
    file: "build/libs/*.jar"
    edge: true
    on:
      branch: master
      tags: true
      jdk: openjdk11
  - provider: pages:git
    local_dir: build/docs
    token: "$GITHUB_API_KEY"
    edge: true
    on:
      branch: master
      tags: true
      jdk: openjdk8
