name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    strategy:
      matrix:
        jdk:
          - 17
          - 21
          - 25
        spring:
          - 5
          - 6
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.jdk }}
        distribution: temurin
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
    - name: Run build
      env:
        SPRING: ${{ matrix.spring }}
      run: ./gradlew check
